name: Run NSE Entry Point Script

on:
  # Manual trigger (optional, keep it)
  workflow_dispatch:

  # Automatic trigger (Monâ€“Fri, 9:15 AM IST)
  schedule:
    - cron: "15 3 * * 1-5"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------
      # Checkout Repository
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------
      # Setup Python
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ----------------------------
      # Install Dependencies
      # ----------------------------
      - name: Install Python dependencies

        run: |
          pip install selenium requests pymongo

      # ----------------------------
      # Run Script
      # ----------------------------
      - name: Run get_entry_point.py
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}      
        run: |
          python get_entry_point.py
